name: flutter_kangoolist
description: KangooList - Mercado Fácil!

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Nativo
  cupertino_icons: ^1.0.2

  # Outros pacotes
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: "^0.13.1"
  uuid: ^4.3.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - "assets/" 

flutter_native_splash:
  color: "#A27EFF"
  image: assets/logo.png
  android_12:
    color: "#A27EFF"
    icon_background_color: "#A27EFF"
    image: assets/logo_1152.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21